postgresdb:
  image: postgres:12
  ports:
    - 5432:5432
  volumes:
    - ./backup:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: mypassword
    POSTGRES_DB: shop
