version: "3.9"
services:
  postgresdb:
    image: postgres:14.5-alpine3.16
    ports:
      - 5432:5432
    volumes:
      - ./backup:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: emails
