name: Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Installing dependencies
        run: npm i
      - name: Executing Linter
        run: npm run lint

  e2e:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Installing dependencies
        run: npm install
      - name: Prisma migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./node_modules/.bin/prisma migrate deploy
      - name: Bundle for production
        run: npm run build
      - name: Executing Cypress
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GH_GIST_ID: ${{ secrets.GH_GIST_ID }}
          GH_TOKEN_GIST: ${{ secrets.GH_TOKEN_GIST }}
        run: npm run e2e
