name: Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Installing dependencies
        run: npm i
      - name: Executing Linter
        run: npm run lint
  e2e:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Installing dependencies
        run: npm install
      - name: Bundle for production
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GH_GIST_ID: ${{ secrets.GH_GIST_ID }}
          GH_TOKEN_GIST: ${{ secrets.GH_TOKEN_GIST }}
        run: npm run build
      - name: Executing Cypress
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GH_GIST_ID: ${{ secrets.GH_GIST_ID }}
          GH_TOKEN_GIST: ${{ secrets.GH_TOKEN_GIST }}
        run: npm run e2e
