name: Tests

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Installing Dependencies
        run: npm install
      - name: Prisma migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./node_modules/.bin/prisma migrate deploy
      - name: Bundle for production
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run build
      - name: Executing Cypress
        run: npm run e2e
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: cypress/videos
